name: SmokeTests

on:
  push:
    branches: [ main ]

jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.vars.outputs.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Version
        id: vars
        shell: bash
        run: |
          version=$(cat VERSION)
          echo ::set-output name=VERSION::$(echo "$version")

  build:
    needs: [ precheck ]
    if: endsWith(${{ needs.precheck.outputs.VERSION }}, '-SNAPSHOT')
    name: 'Build ${{ matrix.job.os }}-${{ matrix.job.sign }}'
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: macos-latest  , sign: gpg   , s: '/', pargs: '-xp docker' }
          - { os: macos-latest  , sign: cosign, s: '/', pargs: '-xp docker' }
          - { os: ubuntu-latest , sign: gpg   , s: '/', pargs: '' }
          - { os: ubuntu-latest , sign: cosign, s: '/', pargs: '' }
          - { os: windows-latest, sign: gpg   , s: '\', pargs: '-xp docker' }
          - { os: windows-latest, sign: cosign, s: '\', pargs: '-xp docker' }
    runs-on: ${{ matrix.job.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradlew-${{ hashFiles('**/gradlew') }}
          restore-keys: |
            ${{ runner.os }}-gradlew-

      - name: Build
        run: ./gradlew build -S

      - name: Unpack
        shell: bash
        run: |
          unzip -d${{ github.workspace }} -qo apps/jreleaser/build/distributions/jreleaser-${{ needs.precheck.outputs.VERSION }}.zip

      - name: Assemble
        shell: bash
        run: |
          ${{ github.workspace }}jreleaser-${{ needs.precheck.outputs.VERSION }}/bin/jreleaser assemble --basedir=${{ github.workspace }} \
            --config-file=${{ github.workspace }}/.github/test-files/jreleaser-${{ matrix.job.sign }}.yml
        env:
          JRELEASER_PROJECT_VERSION: ${{ needs.precheck.outputs.VERSION }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: JReleaser assemble output
        if: always()
        uses: actions/upload-artifact@v2
        with:
          retention-days: 1
          name: 'jreleaser-assemble-${{ matrix.job.os }}-${{ matrix.job.sign }}'
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties

      - name: Release
        shell: bash
        run: |
          ${{ github.workspace }}jreleaser-${{ needs.precheck.outputs.VERSION }}/bin/jreleaser release --basedir=${{ github.workspace }} \
            --config-file=${{ github.workspace }}/.github/test-files/jreleaser-${{ matrix.job.sign }}.yml --dry-run
        env:
          JRELEASER_PROJECT_VERSION: ${{ needs.precheck.outputs.VERSION }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          JRELEASER_COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          JRELEASER_DOCKER_DEFAULT_PASSWORD: ${{ secrets.JRELEASER_DOCKER_PASSWORD }}
          JRELEASER_S3_JRELEASER_REGION: ${{ secrets.S3_REGION }}
          JRELEASER_S3_JRELEASER_BUCKET: ${{ secrets.S3_BUCKET }}
          JRELEASER_S3_JRELEASER_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          JRELEASER_S3_JRELEASER_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v2
        with:
          retention-days: 1
          name: 'jreleaser-release-${{ matrix.job.os }}-${{ matrix.job.sign }}'
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
            out/jreleaser/release/CHANGELOG.md

      - name: Publish
        shell: bash
        run: |
          ${{ github.workspace }}jreleaser-${{ needs.precheck.outputs.VERSION }}/bin/jreleaser publish --basedir=${{ github.workspace }} \
            --config-file=${{ github.workspace }}/.github/test-files/jreleaser-${{ matrix.job.sign }}.yml --dry-run ${{ matrix.job.pargs }}
        env:
          JRELEASER_PROJECT_VERSION: ${{ needs.precheck.outputs.VERSION }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          JRELEASER_COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          JRELEASER_DOCKER_DEFAULT_PASSWORD: ${{ secrets.JRELEASER_DOCKER_PASSWORD }}
          JRELEASER_S3_JRELEASER_REGION: ${{ secrets.S3_REGION }}
          JRELEASER_S3_JRELEASER_BUCKET: ${{ secrets.S3_BUCKET }}
          JRELEASER_S3_JRELEASER_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          JRELEASER_S3_JRELEASER_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v2
        with:
          retention-days: 1
          name: 'jreleaser-publish-${{ matrix.job.os }}-${{ matrix.job.sign }}'
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties