name: Jlink

on:
  workflow_call:
    inputs:
      project-version:
        required: true
        type: string
      java-version:
        default: '11'
        required: false
        type: string
      java-distro:
        default: 'zulu'
        required: false
        type: string
      cache-key:
        required: true
        type: string

jobs:
  jlink:
    name: Jlink
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distro }}

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Cache Gradle wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradlew-${{ hashFiles('**/gradlew') }}
          restore-keys: ${{ runner.os }}-gradlew-

      - name: Cache artifacts
        uses: actions/cache@v3
        id: cache-artifacts
        with:
          key: artifacts-${{ inputs.cache-key }}
          path: |
            plugins/jreleaser/build/libs/
            plugins/jreleaser/build/dependencies/
            plugins/jreleaser/build/distributions/
            plugins/jreleaser-tool-provider/build/libs/*.jar
            plugins/jreleaser-ant-tasks/build/distributions/*.zip

      - name: Cache jlink
        uses: actions/cache@v3
        id: cache-jlink
        with:
          key: jlink-${{ inputs.cache-key }}
          path: out/jreleaser/assemble/jreleaser-standalone/jlink

      - name: Version
        if: endsWith(${{ inputs.project-version }}, '-SNAPSHOT') != true
        run: |
          echo ${{ inputs.project-version }} > VERSION

      - name: Build
        if: steps.cache-artifacts.outputs.cache-hit != 'true'
        run: ./gradlew -Prelease=true build -S

      - name: Jlink
        if: steps.cache-jlink.outputs.cache-hit != 'true'
        uses: jreleaser/release-action@v1
        with:
          version: early-access
          arguments: assemble -s jlink
        env:
          JRELEASER_PROJECT_VERSION: ${{ inputs.project-version }}

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jreleaser-jlink
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties