name: JPackage

on:
  workflow_call:
    inputs:
      project-version:
        required: true
        type: string
      java-version:
        default: '11'
        required: false
        type: string
      java-distro:
        default: 'zulu'
        required: false
        type: string
      cache-key:
        required: true
        type: string

jobs:
  jpackage:
    name: 'JPackage on ${{ matrix.os }}'
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distro }}

      - name: Use GNU tar
        if: ${{ runner.os == 'Windows' }}
        shell: cmd
        run: |
          echo "Adding GNU tar to PATH"
          echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Cache Gradle wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradlew-${{ hashFiles('**/gradlew') }}
          restore-keys: ${{ runner.os }}-gradlew-

      - name: Download artifacts
        uses: actions/cache@v3
        with:
          key: artifacts-${{ inputs.cache-key }}
          path: plugins

      - name: Download jlink
        uses: actions/cache@v3
        with:
          key: jlink-${{ inputs.cache-key }}
          path: out/jreleaser/assemble/jreleaser-standalone/jlink

      - name: Cache jpackage
        uses: actions/cache@v3
        id: cache-jpackage
        with:
          key: jpackage-${{ runner.os }}-${{ inputs.cache-key }}
          path: |
            out/jreleaser/assemble/jreleaser-installer/jpackage/*.pkg
            out/jreleaser/assemble/jreleaser-installer/jpackage/*.msi
            out/jreleaser/assemble/jreleaser-installer/jpackage/*.exe
            out/jreleaser/assemble/jreleaser-installer/jpackage/*.deb
            out/jreleaser/assemble/jreleaser-installer/jpackage/*.rpm

      - name: Version
        if: endsWith(${{ inputs.project-version }}, '-SNAPSHOT') != true
        run: |
          echo ${{ inputs.project-version }} > VERSION

      - name: Build
        if: steps.cache-jpackage.outputs.cache-hit != 'true'
        run: ./gradlew :jreleaser:copyJdksFromCache :jreleaser:setupJdks

      - name: Jpackage
        uses: jreleaser/release-action@v1
        if: steps.cache-jpackage.outputs.cache-hit != 'true'
        with:
          version: early-access
          arguments: assemble -s jpackage -scp
        env:
          JRELEASER_PROJECT_VERSION: ${{ inputs.project-version }}

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jreleaser-jpackage-${{ runner.os }}
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties